# Site settings
title: Talks | Red Panthers - Experts in Ruby on Rails kochi, India
email: tech@redpanthers.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/slides" # the subpath of your site, e.g. /blog/
url: "http://slides.redpanthers.co" # the base hostname & protocol for your site
twitter_username: redpanthershq
github_username:  redpanthers
linkedin_username: redpanthers
instagram_username: redpanthers 

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title

gems:
  - octopress-image-tag
  - octopress-video-tag
  - octopress-codeblock
  - octopress-quote-tag
  - octopress-codefence
  - octopress-solarized
  - octopress-gist
